language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo test

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target/doc
  skip_cleanup: true
  script:
    - cargo doc
  on:
    branch: main
    rust: nightly
